---
- hosts: server1
  vars_files:
     - vars.yml
  remote_user: root
  tasks:
  
  - name: Configure freetds to connect to MSSQL database
    blockinfile:
       dest: /etc/freetds/freetds.conf
       block: |
          #Our Database Connection for MSSQL alias
          [MSSQL]
          	host=MSSQL
          	port=1443
          	tds version = 7.0
  
  - name: copy odbcinst.ini  config file
    copy: src=/home/ubuntu/ansible-dir/files/odbcinst.ini dest=/etc/odbcinst.ini owner=root  mode=0644
  - name: copy odbc.ini  config file
    copy: src=/home/ubuntu/ansible-dir/files/odbc.ini dest=/etc/odbc.ini owner=root  mode=0644
  
  - name: checkout latest web app code
    git: repo={{code_repo}}  dest={{app_dir}} accept_hostkey=True
